### ISSUE TITLE
Place text near the highlighted view.

### ISSUE THREAD

**Issue by lynnardd** [Popalay/Tutors#5]

**Comment by Popalay** [comment]
@lynnardd Check latest version

**Comment by lynnardd** [comment]
Thanks. Will check out tomorrow

On 16 Feb 2017 6:54 PM, Denis Nikiforov <notifications@github.com> wrote:

@lynnardd<https://github.com/lynnardd> Check latest version

**Comment by lynnardd** [comment]
Still persists tho. I think it would be better to remove the line and just place the text underneath or on top the view being highlighted

**Comment by Popalay** [comment]
@lynnardd I will think about your suggestion
