### ISSUE TITLE
Text & Lines misses when using NestedScrollView

### ISSUE THREAD

**Issue by RankoR** [Popalay/Tutors#6]
Version 1.0.4.

I have a nested scroll view with two buttons:

```
<android.support.v4.widget.NestedScrollView
            android:id="@+id/scroll"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clipToPadding="false"
            android:fillViewport="true"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

   <LinearLayout>
       <Button/>
       <Button/>
   </LinearLayout>
</android.support.v4.widget.NestedScrollView>
```

I want to show tutorial for these two buttons. The first one misses a lot, the second — a little bit:

![First button](https://i.imgur.com/nsp7lhY.png)
![Second button](https://i.imgur.com/obev1ZP.png)

If I'll show tutorial for the second button only:

![Second button only](https://i.imgur.com/mNWeRLQ.png)

I've tried to add a delay in 2 seconds before displaying the tutorial and nothing changed.

**Comment by Popalay** [comment]
I will try to fix it

**Comment by Popalay** [comment]
@RankoR I couldn't reproduce your issue
![screenshot_1491756492](https://cloud.githubusercontent.com/assets/10115268/24839138/bab999f2-1d5d-11e7-9cdd-de3b619dedbb.png)
![screenshot_1491756504](https://cloud.githubusercontent.com/assets/10115268/24839139/bc4c6b6e-1d5d-11e7-9f57-91478fc84c50.png)
